apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
data:
  config.yaml: |
    tunnel: {{ .Values.cloudflare.tunnelName }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    warp-routing:
      enabled: {{ .Values.cloudflare.enableWarp }}
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      {{- with .Values.cloudflare.ingress }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      - service: http_status:404
